project:
  type: website
  output-dir: docs
  render: 
    - index_fr.qmd
    - index_ang.qmd
    - Statistiques.qmd

website:
  reader-mode: true 
  repo-url: https://github.com/elqemmahdoha/TEAM_PROJECT
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  title: "Montpellier à Vélo"
  navbar:
    tools:
      - icon: database
        href: https://data.montpellier3m.fr/dataset/comptages-velo-et-pieton-issus-des-compteurs-de-velo
        text: Data
      - icon: github
        href: https://github.com/elqemmahdoha/TEAM_PROJECT
        text: GitHub
    right:
      - href: index_fr.qmd
        text: Fr
      - href: index_ang.qmd
        text: En
    left: 
      - href: Statistiques.qmd
        text: Graphes


format:
  html:
    smooth-scroll: true
    theme:
      light: [cosmo, lightmode.scss]
      dark: [cosmo, darkmode.scss]
    toc: true         
    toc-location: left
    toc-title: Index
    css: styles.css  
    theme-switcher: true
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1.5rem
