---
titre: "Description graphiques des données"
output: html
---
::: {.content-visible when-profile="fr0,fr"}

# Retraits et Dépôts des vélos Vélomagg

Découvrez les tendances de retrait et de dépôt des vélos Vélomagg grâce à un graphique interactif qui présente, pour chaque jour de la semaine, le nombre de dépôts et de retraits dans chaque station. Cette visualisation permet de suivre l'évolution quotidienne des flux de vélos et de mieux comprendre les variations de fréquentation d'une station à l'autre, offrant ainsi une analyse approfondie des habitudes d'utilisation tout au long de la semaine.

<iframe src="graphique_interactif.html" width="100%" height="900px">
</iframe>

# Moyenne des intensités par mois 

<iframe src="average_intensity_month.html" width="100%" height="500px">
</iframe>

# Figure 

<iframe src="polar_figure.html" width="100%" height="500px">
</iframe>
:::


::: {.content-visible when-profile="en"}
# Withdrawals and Deposits of Vélomagg Bikes

Explore the trends of bike withdrawals and deposits at Vélomagg through an interactive chart that shows, for each day of the week, the number of deposits and withdrawals at each station. This visualization allows you to track the daily flow of bikes and better understand station-to-station variations in usage, providing an in-depth analysis of usage patterns throughout the week.

<iframe src="graphique_interactif.html" width="100%" height="900px">
</iframe>

# Average Intensity by Month 

<iframe src="average_intensity_month.html" width="100%" height="500px">
</iframe>

# Figure 

<iframe src="polar_figure.html" width="100%" height="500px">
</iframe>
:::