project:
  output-dir: ../docs
  render: 
    - siteweb/index.qmd
    - siteweb/stat.qmd
    - siteweb/about.qmd

website:
  reader-mode: true
  repo-url: https://github.com/elqemmahdoha/TEAM_PROJECT/tree/main/siteweb
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  title: "Pédaler à Montpellier"
  navbar:
    right:
      - href: fr/index.html
        text: Français
      - href: en/index.html
        text: English
    left:
      - href: index.qmd
        text: Exploration Dynamique
      - href: stat.qmd       
        text: Comptage Vélomagg
      - href: about.qmd       
        text: À propos
    tools:
      - icon: database
        href: https://data.montpellier3m.fr/dataset/comptages-velo-et-pieton-issus-des-compteurs-de-velo
        text: Data
      - icon: github
        href: https://github.com/elqemmahdoha/TEAM_PROJECT
        text: GitHub

lang: fr 

format:
  html:
    smooth-scroll: true
    theme:
      light: [cosmo, lightmode.scss]
      dark: [cosmo, darkmode.scss]
    toc: true         
    toc-location: left
    toc-title: Index
    css: styles.css  
    theme-switcher: true
    grid:
      sidebar-width: 250px
      body-width: 1050px
      margin-width: 200px
      gutter-width: 3.5rem