project:
  output-dir: ../docs/en
  render: 
    - index.qmd
    - stat.qmd
    - about.qmd

website:
  reader-mode: true
  repo-url: https://github.com/elqemmahdoha/TEAM_PROJECT
  repo-actions: [source, issue]
  page-navigation: true
  back-to-top-navigation: true
  title: "Cycling in Montpellier"
  navbar:
    right:
      - href: ../fr/index.html
        text: Français
      - href: ../en/index.html
        text: English
    left:
      - href: index.qmd
        text: Dynamic Exploration
      - href: stat.qmd       
        text: Vélomagg Counting
      - href: about.qmd       
        text: About
    tools:
      - icon: database
        href: https://data.montpellier3m.fr/dataset/comptages-velo-et-pieton-issus-des-compteurs-de-velo
        text: Data
      - icon: github
        href: https://github.com/elqemmahdoha/TEAM_PROJECT
        text: GitHub

lang: en

format:
  html:
    smooth-scroll: true
    theme:
      light: [cosmo, lightmode.scss]
      dark: [cosmo, darkmode.scss]
    toc: true         
    toc-location: left
    toc-title: Index
    css: styles.css  
    theme-switcher: true
    grid:
      sidebar-width: 250px
      body-width: 1050px
      margin-width: 200px
      gutter-width: 3.5rem